version: "3.9"

services:
  twisted-ctf_1_2_3_5:
    build: .
    container_name: twisted_ctf_1_2_3_5
    ports:
      - "9001:9001"
      - "9002:9002"
      - "9003:9003"
      - "9005:9005"
    restart: unless-stopped
