version: '3'
services:
  mainquest:
    build: 
      context: ./mainquest
    ports:
      - "2121:21"
      - "80:80"
      - "8000:8000"
      - "2222:22"
    container_name: final_mainquest
    hostname: final-boss
